### PR TITLE
fix(doc): correct link from dialog to manual bootstraping

### PR DESCRIPTION
**Pull request by Alexander-Taran**
fixes https://github.com/aurelia/documentation/issues/346

### CODE REVIEW

**Comment by Alexander-Taran** [comment]
don't know if it is the right way or if json file should be modified as well..

**Comment by EisenbergEffect** [comment]
Actually, this is just the test documentation. The real doc that needs fixing is in the framework repository, under the doc folder. Would you be interested in submitting a PR to that? Sorry for the confusion!

**Comment by EisenbergEffect** [comment]
Oops! I think the real doc is in the dialog repo. Sorry!

**Comment by Alexander-Taran** [comment]
Will hunt it down..

**Comment by Alexander-Taran** [comment]
https://github.com/aurelia/dialog/pull/341

**Pull request closed without merging**
